### ISSUE TITLE
transpor projeto para as novas dependencias kotlinx.

### ISSUE THREAD

**Issue by neuberfran** [neuberfran/MyApplication2#1]
Este projeto é baseado nesse:

https://github.com/neuberfran/Marvel/pull/1

**quando eu subo as dependencias abaixo, de:** 

 implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:0.19.3'
 implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:0.19.3'
 implementation 'ru.gildor.coroutines:kotlin-coroutines-retrofit:0.8.2'

**para:**

 implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.2.1'
 implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.1.1'
 implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.2.1'

obtenho o erro abaixo(prin screen) , e se transformo a classe CharactersAdapter em abstrata, obtenho erro em:  
```
  private val adapter: CharactersAdapter by lazy {
        CharactersAdapter()
    }
```

do pacote: CharactersActivity.

![issue](https://user-images.githubusercontent.com/38701397/60404267-b1570c00-9b7d-11e9-8240-793ca8c67b3b.png)

**Comment by AhmadAyyaz1993** [comment]
You are missing your overriden method onCreateViewHolder from your adapter class

**Comment by neuberfran** [comment]
![image](https://user-images.githubusercontent.com/38701397/61234194-d5cbf000-a708-11e9-8d94-05838e612de3.png)

**Comment by AhmadAyyaz1993** [comment]
it is gonna be like this: 

`override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): VH{
        View inflater = LayoutInflater.from(parent?.context).inflate(R.layout.item_character, parent, false)
        return MovieViewHolder(inflater, parent)
    }`

**Comment by neuberfran** [comment]
![image](https://user-images.githubusercontent.com/38701397/61570721-e790f880-aa64-11e9-82ca-62cd10820983.png)

**Comment by neuberfran** [comment]
abstract but not solved in other local
![image](https://user-images.githubusercontent.com/38701397/61573100-406d8a80-aa7f-11e9-86af-a0fce9cd15e0.png)


![image](https://user-images.githubusercontent.com/38701397/61573088-1a47ea80-aa7f-11e9-8d68-df48da4e0b12.png)

**Comment by neuberfran** [comment]
![image](https://user-images.githubusercontent.com/38701397/61573120-7dd21800-aa7f-11e9-82f2-f17defd02b16.png)

**Comment by neuberfran** [comment]
![image](https://user-images.githubusercontent.com/38701397/61573124-90e4e800-aa7f-11e9-933e-cf5887b05867.png)

**Comment by AhmadAyyaz1993** [comment]
replace your parent with p0.

**Comment by neuberfran** [comment]
kotlin.NotImplementedError: An operation is not implemented: not implemented
![Captura de Tela 2019-07-27 às 20 33 28](https://user-images.githubusercontent.com/38701397/62001829-f4899980-b0ad-11e9-8dcd-7ec13cc79557.png)

kotlin.NotImplementedError: An operation is not implemented: not implemented

**Comment by neuberfran** [comment]
Solved 28/7/19
